version: '3.8' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
